[options]
HoldPkg      = pacman glibc manjaro-system
Architecture = auto
Color
CheckSpace
ParallelDownloads = 2
DownloadUser = alpm


SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional


[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

