#!/usr/bin/env bash

##################################################
# Mars OS Installer v1.1
# Main Launcher
##################################################

set -e


##################################################
# Error Handling
##################################################

trap 'die "Installer failed at line $LINENO"' ERR



##################################################
# Paths
##################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

LIB_DIR="$SCRIPT_DIR/lib"
WIZARD_DIR="$SCRIPT_DIR/wizard"
INSTALL_DIR="$SCRIPT_DIR/install"



##################################################
# Libraries
##################################################

source "$LIB_DIR/util.sh"
source "$LIB_DIR/config.sh"
source "$LIB_DIR/ui.sh"



##################################################
# Requirements
##################################################

check_requirements() {

    require_command dialog
    require_command pacman
    require_command arch-chroot

}



##################################################
# Wizard Runner
##################################################

run_wizard() {


    for MODULE in "$WIZARD_DIR"/*.sh; do


        if [[ -f "$MODULE" ]]; then


            log "Running wizard module: $MODULE"



            bash "$MODULE" || die \
"\
Wizard failed:

$MODULE
"



        fi


    done


}



##################################################
# Install Runner
##################################################

run_install() {


    for MODULE in "$INSTALL_DIR"/*.sh; do


        if [[ -f "$MODULE" ]]; then


            log "Running install module: $MODULE"



            bash "$MODULE" || die \
"\
Installation failed:

$MODULE
"



        fi


    done


}



##################################################
# Main
##################################################

main() {


    check_requirements



    config_init

    config_clear



    log "Mars OS Installer v1.1 started"



    ui_msgbox \
        "Mars OS Installer v1.1" \
"\
Welcome to Mars OS.

This installer will guide you through
configuring and installing your system.
"



    run_wizard


    run_install



    ui_msgbox \
        "Complete" \
"\
Mars OS installation finished.

You may now reboot into your new system.
"



}



main
